- job:
    tenant: Test_api
    description: EPG associated with BD、ANP、Domain
    tasklist:
        - task:
            description: create EPG
            template: ./template_epg.json
            sourcedata: ./data.xlsx
- job:
    tenant: Test_api
    description: Static Leafs
    tasklist:
        - task:
            description: binding leafs
            template: ./template_static_leaf.json
            sourcedata: ./data.xlsx